
import Model from 'react-native-models';

export default class UserModel extends Model {
  static get className() {
      return "UserModel";
  }
  constructor(){
      super({
          BankAccountBIC: "String",
          BankAccountIBAN: "String",
          BankAccountOwnerAddress: "String",
          BankAccountOwnerCity: "String",
          BankAccountOwnerCountry: "String",
          BankAccountOwnerName: "String",
          BankAccountPostalcode: "String",
          CompanyName: "String",
          CompanyNumber: "String",
          beneficiary_id: "String",
          card_number: "String",
          cmp_cnaps_number: "String",
          cmp_date_creation: "String",
          cmp_id: "String",
          cmp_logo: "String",
          cmp_name: "String",
          cmp_address: "String",
          cmp_tva_number: "String",
          company_id: "String",
          company_name: "String",
          countries_id: "String",
          country: "String",
          flowlu_account_id: "Number",
          flowlu_account_type: "Number",
          gen_id: "Number",
          is_deleted: "Number",
          isregistered: "Number",
          lang_id: "String",
          leetchi_user_id: "String",
          leetchi_wallet_id: "String",
          logged_in: "Boolean",
          login: "String",
          mem_uid: "Number",
          mem_additional_phone: "String",
          mem_additional_phone_verified: "Number",
          mem_address: "String",
          mem_city: "String",
          mem_cnaps_appr_num: "String",
          mem_country_code: "String",
          mem_dob: "String",
          mem_email: "String",
          mem_fname: "String",
          mem_hourly_rate: "String",
          mem_id: "Number",
          mem_lat: "String",
          mem_lname: "String",
          mem_lng: "String",
          mem_mobile: "String",
          mem_phone: "String",
          mem_photo: "String",
          mem_type: "Number",
          mem_uid: "String",
          pass: "String",
          phone_no_verified: "Boolean",
          place_id: "String",
          provider_id: "Number",
          salt: "String",
          session_id: "String",
          short_code: "String",
          sm_id: "String",
          status_id: "Number",
          urole_id: "Number",
          us_id: "Number",
          user_address: "String",
          user_allow_noti: "Number",
          user_allow_sound: "Number",
          user_city: "String",
          user_country: "String",
          user_date_created: "String",
          user_email: "String",
          user_full_name: "String",
          user_id: "Number",
          user_last_login: "String",
          user_last_updated: "String",
          user_lat: "String",
          user_lng: "String",
          user_name: "String",
          user_pass_phrase: "String",
          user_password: "String",
          user_phone_verified: "Number",
          user_rating: "String",
          user_total_rating: "String",
          utype_id: "String",
          utype_name: "String",

      });
    }
}
